### ISSUE TITLE
Cannot build following the instructions

### ISSUE THREAD

**Issue by zyfdegh** [MysteriumNetwork/contracts#7]
I followed the README file to build contracts in my local machine, but an error occured.

This is my VirtualBox machine:
* OS: CentOS 7.3
* Kernel: x86_64 Linux 3.10.0
* Python: 3.5.1
* pip: 9.0.1
* solc: 0.4.11+commit.68ef5810.Linux.g++

This is the code:
* Commit: eee474da (2017-06-12)
* Branch: master

After I execute this command, it printed an errors 
```sh
$ pip install -e ico
Directory 'ico' is not installable. File 'setup.py' not found.
```

And when I continue to compile, it printed the error stack
```sh
$ populus compile
Traceback (most recent call last):
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/populus/cli/compile_cmd.py", line 41, in compile_cmd
    _, compiled_contract_data = compile_project_contracts(project, compiler_settings)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/populus/compilation.py", line 54, in compile_project_contracts
    compiled_contracts = compile_files(all_source_paths, **compiler_settings)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/solc/main.py", line 123, in compile_files
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/solc/utils/string.py", line 67, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/root/GOPATH/src/github.com/MysteriumNetwork/contracts/venv/lib/python3.5/site-packages/solc/wrapper.py", line 151, in solc_wrapper
    stderr_data=stderrdata,
solc.exceptions.SolcError: An error occurred during execution
        > command: `solc --optimize --combined-json abi,bin,bin-runtime,devdoc,metadata,userdoc zeppelin=zeppelin ico=ico contracts/Crowdsale.sol contracts/CrowdsaleToken.sol contracts/FinalizeAgent.sol contracts/FractionalERC20.sol contracts/GnosisWallet.sol contracts/Haltable.sol contracts/IntermediateVault.sol contracts/MintableToken.sol contracts/MultiVault.sol contracts/MysteriumCrowdsale.sol contracts/MysteriumPricing.sol contracts/MysteriumToken.sol contracts/PricingStrategy.sol contracts/ReleasableToken.sol contracts/SafeMathLib.sol contracts/StandardToken.sol contracts/UpgradeAgent.sol contracts/UpgradeableToken.sol contracts/MysteriumTokenDistribution.sol contracts/test/SimpleReleaseAgent.sol contracts/test/TestMigrationTarget.sol`
        > return code: `1`
        > stderr:

        > stdout:
        contracts/FractionalERC20.sol:3:1: Error: Source "zeppelin/contracts/token/ERC20.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/token/ERC20.sol";
^------------------------------------------^
contracts/Haltable.sol:3:1: Error: Source "zeppelin/contracts/ownership/Ownable.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/ownership/Ownable.sol";
^------------------------------------------------^
contracts/MintableToken.sol:1:1: Error: Source "zeppelin/contracts/token/ERC20.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/token/ERC20.sol";
^------------------------------------------^
contracts/MintableToken.sol:2:1: Error: Source "zeppelin/contracts/ownership/Ownable.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/ownership/Ownable.sol";
^------------------------------------------------^
contracts/MysteriumPricing.sol:6:1: Error: Source "zeppelin/contracts/ownership/Ownable.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/ownership/Ownable.sol";
^------------------------------------------------^
contracts/MysteriumTokenDistribution.sol:7:1: Error: Source "zeppelin/contracts/ownership/Ownable.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/ownership/Ownable.sol";
^------------------------------------------------^
contracts/ReleasableToken.sol:3:1: Error: Source "zeppelin/contracts/ownership/Ownable.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/ownership/Ownable.sol";
^------------------------------------------------^
contracts/ReleasableToken.sol:4:1: Error: Source "zeppelin/contracts/token/ERC20.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/token/ERC20.sol";
^------------------------------------------^
contracts/StandardToken.sol:4:1: Error: Source "zeppelin/contracts/token/ERC20.sol" not found: Unknown exception in read callback.
import 'zeppelin/contracts/token/ERC20.sol';
^------------------------------------------^
contracts/StandardToken.sol:5:1: Error: Source "zeppelin/contracts/SafeMath.sol" not found: Unknown exception in read callback.
import 'zeppelin/contracts/SafeMath.sol';
^---------------------------------------^
contracts/UpgradeableToken.sol:3:1: Error: Source "zeppelin/contracts/token/ERC20.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/token/ERC20.sol";
^------------------------------------------^
```

So, is this caused by the wrong version of `python` or `pip` or `solc` ? 
(I wonder if I need to use the exact version of the above software.)

Do I need to install zepplin manually?

Any advice or articles to help me build this contract, many thanks.

**Comment by zyfdegh** [comment]
Oh, it's my own mistake. I forgot to pull git submodules. Simply fix it by
```sh
git submodule update --init --recursive
```
